version: "1"

services:
  og-api:
    build: ./
    container_name: OgnareAPIRest
    restart: always
    ports:
      - 3030:3030
    volumes:
      - .:/user/api

volumes:
  pgdata:
    driver: local
