version: "2.10.2"

services:
  og-api:
    build: ./
    container_name: OgnareAPIRest
    restart: always
    ports:
      - 3030:3030
    volumes:
      - .:/user/api
    depends_on:
      - database

volumes:
  pgdata: 
    driver: local