version: "2.2"

services:
  og-api:
    build: .
    command: npm run application
    restart: always
    environment:
      - ID_PROJECT_WELCOME=${ID_PROJECT_WELCOME}
    env_file:
      - .env
    ports:
      - 3030:3030
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
