version: "2.2"

services:
  og-api:
    build: .
    container_name: OgnareAPIRest
    # restart: always
    ports:
      - 3030:3030
    volumes:
      - ./:./usr/api/
      - node_modules:./usr/api/node_modules
