version: "2.2"

networks:
  local-rede:
    driver: bridge
services:
  og-cache:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    volumes:
      - /local-data/:/data
    networks:
      - local-rede

  og-api:
    build: .
    command: npm start
    restart: always
    env_file:
      - .env
    ports:
      - 3030:3030
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - og-cache
    links:
      - "og-cache"
    networks:
      - local-rede
