name: Continuous integrations Ognare

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of repositories
        uses: actions/checkout@v1

      - name: Deploy of application
        uses: easingthemes/ssh-deploy@v2.0.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          remote-user: ${{ secrets.REMOTE_USER }}
          remote-host: ${{ secrets.REMOTE_HOST }}
          local-folder: ./
          remote-folder: /home/ognare.api.com
