name: Continuous integrations Ognare

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of repositories
        uses: actions/checkout@v3

      - name: Deploy of application
        uses: easingthemes/ssh-deploy@v2.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          EXCLUDE: "/dist/, /node_modules/"
