name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: run-unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of repositories
        uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - run: npm run test
